version: '3.8'

services:
  grafana:
    # image: grafana/grafana-oss:11.2.2  # Use a specific version; replace with grafana/grafana-enterprise if needed
    image: grafana/grafana:12.0.1
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana  # Bind mount for persistence
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_DATABASE_TYPE=${GF_DATABASE_TYPE}
      - GF_DATABASE_HOST=${GF_DATABASE_HOST}
      - GF_DATABASE_NAME=${GF_DATABASE_NAME}
      - GF_DATABASE_USER=${GF_DATABASE_USER}
      - GF_DATABASE_PASSWORD=${GF_DATABASE_PASSWORD}
      - GF_SECURITY_ALLOW_EMBEDDING=${GF_SECURITY_ALLOW_EMBEDDING}
      - GF_SECURITY_COOKIE_SAMESITE=${GF_SECURITY_COOKIE_SAMESITE}
      - GF_LOG_LEVEL=${GF_LOG_LEVEL}
    deploy:
      resources:
    # image: grafana/grafana-oss:11.2.2  # Use a specific version; replace with grafana/grafana-enterprise if needed
        limits:
          cpus: '0.5'  # Allocate 0.5 CPU cores
          memory: 500M   # Allocate 500MB memory
        reservations:
          cpus: '0.5'  # Reserve at least 0.5 CPU core
          memory: 250M   # Reserve 250MB memory
    secrets:
      - grafana_admin_password
      - db_password

  db:
    image: postgres:16-alpine  # Lightweight Alpine variant for security
    container_name: grafana-db
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
      - POSTGRES_PASSWORD__FILE=/run/secrets/db_password
    secrets:
      - db_password

volumes:
  pgdata: {}  # Named volume for database persistence

secrets:
  grafana_admin_password:
    file: ./secrets/grafana_admin_password.txt  # Create this file with a strong password
  db_password:
    file: ./secrets/db_password.txt  # Create this file with a strong password