[server]
protocol = http
http_addr =
http_port = 3000
domain = localhost
root_url = %(protocol)s://%(domain)s:%(http_port)s/

[security]
admin_user = admin
admin_password = admin

[database]
type = postgres
host = db:5432
name = grafana
user = grafana
password = admin
ssl_mode = disable

[smtp]
enabled = true
host = ${SMTP_HOST}
user = ${SMTP_USER}
password = ${SMTP_PASSWORD}
from_address = ${SMTP_FROM_ADDRESS}
from_name = ${SMTP_FROM_NAME}
skip_verify = ${SMTP_SKIP_VERIFY:-false}
# startTLS_policy = ${SMTP_STARTTLS_POLICY:-OpportunisticStartTLS}

# [alerting]
# enabled = true
# execute_alerts = true
# error_or_timeout = alerting
# nodata_or_nullvalues = no_data
# concurrent_render_limit = 5

[emails]
welcome_email_on_sign_up = false
